### ISSUE TITLE
full acceleration mojave but blank internal still

### ISSUE THREAD

**Issue by THEDEVIOUS1** [balopez83/One-Mix-3-Hackintosh#1]
check your messages on discord...if i havent sent by the time u get this i will in the next few following minutes but long story short the regular config is your untouched version and the configMINIMUM is one with the bare minimum amount of changes i think i can make to enable acceleration and get the internal screen detected but blank as noted
[EFI.zip](https://github.com/balopez83/One-Mix-3-Hackintosh/files/3507935/EFI.zip)

**Comment by balopez83** [comment]
I just uploaded a new EFI. If you have time try the new files as it has updated Kexts and heavily modified config file. The config file is bloated but I plan to clean it up once I make a few more tests. Currently I have both the micro HDMI port and USB-C working with the internal display working properly on macOS Sierra. Some key issues you will want to be aware of are: 1. you will need to add a fake intel identifier if you need to install macOS again with this EFI. 2. you must boot with no external monitor plugged into any of the ports (very important). Once you reach the login screen or desktop you can then plug in and it should activate the screen right away. 3. If after plugging in an external monitor the internal flashes on and off, let it do this for a min or two and then it should start working. (I think it is discovering the monitor information)
