### ISSUE TITLE
[Fixed] Audio is working so smooth now! 

### ISSUE THREAD

**Issue by pokemonerdotcom** [balopez83/One-Mix-3-Hackintosh#4]
I saw you try to use VoodooHDA and AppleALC together But VoodooHDA has some bugs. Anyway, With AppleALC v1.4.3, The Audio is working with layout-id = 100. It's the same as GPD P2 Max! I tested on my One Mix 3s and it's working perfectly! You can try to test and update your EFI if you want!

**Comment by balopez83** [comment]
Thanks for letting me know. I have actually completely overhauled my EFI and hope to get it posted soon and have removed the VoodooHDA. Before I upload though I need to determine the battery patch used on the GPD Pocket and fix brightness but beyond that everything else appears to be working including sleep..

**Comment by pokemonerdotcom** [comment]
I checked and not patch on DSDT about fix brightness. You can try to follow this guide to fix brightness: https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightfixup-kext.218222/ it's working on my device. About battery patch, hmm I don't know ... I try to fix CPUPowerManager by Native but I don't know it's working or not :)) I will try to research soon. If I can fix sleep, Shutdown problem, I will feedback soon!

**Comment by balopez83** [comment]
@pokemonerdotcom I just wanted to let you know that I am going to discontinue working on this project as I am unable to resolve the custom Intel graphics layout. I have uploaded several other EFI attempts and all my other non-functional ones as well to hopefully help you get further in getting it running. If you have questions or need help I will be happy to still assist where I can but I am selling my OneMix 3 and changing to another computer that I know has functional standard Intel graphics. Also FYI the touch screen can work on the OMY3 as I was able to get it partially functional for a few minutes but it will require additional work and also a fully and properly set up USB port layout.

**Comment by lazd** [comment]
@balopez83 any hints on the touch screen setup? Which DSDT patches did you apply, which KEXTs, etc?

**Comment by balopez83** [comment]
Hi @lazd, the DSDT patches that were applied were only the two standard ones provided for in the voodooi2c instructions as well as the windows10 patch. I had also included the standard voodooi2c and voodooi2chid kext as well. I ended up selling this device as I could not fix the graphics problems and so did not look into this any further. Sorry I cannot provide more help on this one.
